# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV.fetch("D3_DATE_FORMAT", '%y-%m-%d').dump %>  # .dump is needed as the value may start by a '%', see https://github.com/tenderlove/psych/issues/75
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV.fetch("RAILS_LOCALE", 'en').dump %>
  app_locale: <%= ENV.fetch("APP_LOCALE", 'en').dump %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  intl_locale: <%= ENV["INTL_LOCALE"] %>
  intl_currency: <%= ENV["INTL_CURRENCY"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  postgresql_language_analyzer: <%= ENV.fetch("POSTGRESQL_LANGUAGE_ANALYZER", 'simple') %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  openlab_ssl_verify: <%= ENV.fetch("OPENLAB_SSL_VERIFY", true) %>
  openlab_ssl_verify_peer: <%= ENV.fetch("OPENLAB_SSL_VERIFY_PEER", true) %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
  max_cao_size: <%= ENV["MAX_CAO_SIZE"] %>
  max_import_size: <%= ENV["MAX_IMPORT_SIZE"] %>
  max_proof_of_identity_file_size: <%= ENV["MAX_PROOF_OF_IDENTITY_FILE_SIZE"] %>
  disk_space_mb_alert: <%= ENV["DISK_SPACE_MB_ALERT"] %>
  adminsys_email: <%= ENV["ADMINSYS_EMAIL"] %>
  allow_insecure_http: <%= ENV.fetch("ALLOW_INSECURE_HTTP", false) %>
  locked_settings: <%= ENV.fetch("LOCKED_SETTINGS", 'uuid,origin').split(/,/) %>